name: Mark
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.2 <4.0.0"

dependencies:
  background_downloader: ^7.6.0
  cupertino_icons: ^1.0.2
  dio: ^5.1.1
  easy_stepper: ^0.7.3
  elegant_notification: ^1.10.1
  fcm_config: ^3.5.1
  file_picker: ^5.3.3
  flex_color_picker: ^3.2.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.1.1+1
  flutter_rating_bar: ^4.0.1
  flutter_secure_storage: ^8.0.0
  font_awesome_flutter: ^10.4.0
  get: ^4.6.5
  google_fonts: ^4.0.3
  http: ^1.1.0
  intl: ^0.18.0
  mask: ^1.0.5
  pinch_zoom_release_unzoom: ^1.0.1
  salomon_bottom_bar: ^3.3.2
  sqflite: ^2.2.8+4

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
