import 'package:flutter_secure_storage/flutter_secure_storage.dart';

Map colorNames = {
  "Black": "Preto",
  "Navy Blue": "Azul marinho",
  "Dark Blue": "Azul escuro",
  "Blue": "Azul",
  "Stratos": "Stratos",
  "Swamp": "Pântano",
  "Resolution Blue": "Azul resolução",
  "Deep Fir": "Abeto profundo",
  "Burnham": "Burnham",
  "Klein Blue": "Azul Klein",
  "Prussian Blue": "Azul prussiano",
  "Midnight Blue": "Midnight Blue",
  "Smalt": "Smalt",
  "Deep Teal": "Deep Teal",
  "Cyprus": "Cyprus",
  "Kaitoke Green": "Kaitoke Green",
  "Cobalt": "Cobalt",
  "Crusoe": "Crusoe",
  "Sherpa Blue": "Sherpa Blue",
  "Endeavour": "Endeavour",
  "Camarone": "Camarone",
  "Science Blue": "Science Blue",
  "Blue Ribbon": " Blue Ribbon",
  "Tropical Rain Forest": "Tropical Rain Forest",
  "Allports": "Allports",
  "Deep Cerulean": "Deep Cerulean",
  "Lochmara": "Lochmara",
  "Azure Radiance": "Azure Radiance",
  "Teal": "Teal",
  "Bondi Blue": "Bondi Blue",
  "Pacific Blue": "Pacific Blue",
  "Persian Green": "Persian Green",
  "Jade": "Jade",
  "Caribbean Green": "Caribbean Green",
  "Robin's Egg Blue": "Robin's Egg Blue",
  "Green": "Green",
  "Spring Green": "Spring Green",
  "Cyan Aqua": "Cyan Aqua",
  "Blue Charcoal": "Blue Charcoal",
  "Midnight": "Midnight",
  "Holly": "Holly",
  "Daintree": "Daintree",
  "Cardin Green": "Cardin Green",
  "County Green": "County Green",
  "Astronaut Blue": "Astronaut Blue",
  "Regal Blue": "Regal Blue",
  "Aqua Deep": "Aqua Deep",
  "Orient": "Orient",
  "Blue Stone": "Blue Stone",
  "Fun Green": "Fun Green",
  "Pine Green": "Pine Green",
  "Blue Lagoon": "Blue Lagoon",
  "Deep Sea": "Deep Sea",
  "Green Haze": "Green Haze ",
  "English Holly": "English Holly",
  "Sherwood Green": "Sherwood Green",
  "Congress Blue": "Congress Blue",
  "Evening Sea": "Evening Sea",
  "Bahama Blue": "Bahama Blue",
  "Observatory": "Observatory",
  "Cerulean": "Cerulean",
  "Tangaroa": "Tangaroa",
  "Green Vogue": "Green Vogue",
  "Mosque": "Mesquita",
  "Midnight Moss": "Midnight Moss",
  "Black Pearl": "Black Pearl",
  "Blue Whale": "Blue Whale",
  "Zuccini": "Zuccini",
  "Teal Blue": "Teal Blue",
  "Deep Cove": "Deep Cove",
  "Gulf Blue": "Gulf Blue",
  "Venice Blue": "Venice Blue",
  "Watercourse": "Watercourse",
  "Catalina Blue": "Catalina Blue",
  "Tiber": "Tiber",
  "Gossamer": "Gossamer",
  "Niagara": "Niagara",
  "Tarawera": "Tarawera",
  "Jaguar": "Jaguar",
  "Black Bean": "Black Bean",
  "Deep Sapphire": "Deep Sapphire",
  "Elf Green": "Elf Green",
  "Bright Turquoise": "Bright Turquoise",
  "Downriver": "Downriver",
  "Palm Green": "Palm Green",
  "Madison": "Madison",
  "Bottle Green": " Bottle Green",
  "Deep Sea Green": "Deep Sea Green",
  "Salem": "Salem",
  "Black Russian": "Black Russian",
  "Dark Fern": "Dark Samambaia",
  "Japanese Laurel": "Japanese Laurel",
  "Atoll": "Atoll",
  "Cod Gray": "Cod Grey",
  "Marshland": "Marshland",
  "Gordons Green": "Gordons Green",
  "Black Forest": "Black Forest ",
  "San Felix": "San Felix",
  "Malachite": "Malachite",
  "Ebony": "Ebony",
  "Woodsmoke": "Woodsmoke",
  "Racing Green": "Racing Green",
  "Surfie Green": "Surfie Green",
  "Blue Chill": "Blue Chill",
  "Black Rock": "Black Rock",
  "Bunker": "Bunker",
  "Aztec": "Aztec",
  "Bush": "Bush",
  "Cinder": "Cinder",
  "Firefly": "Firefly",
  "Torea Bay": "Torea Bay",
  "Vulcan": "Vulcan",
  "Green Waterloo": "Green Waterloo",
  "Eden": "Eden",
  "Arapawa": "Arapawa",
  "Ultramarine": "Ultmarine",
  "Elephant": "Elephant",
  "Jewel": "Jewel",
  "Diesel": "Diesel",
  "Asphalt": "Asphalt",
  "Blue Zodiac": "Blue Zodiac",
  "Parsley": "Salsa",
  "Nero": "Nero",
  "Tory Blue": "Tory Blue",
  "Bunting": "Bunting",
  "Denim": "Denim",
  "Genoa": "Genoa",
  "Mirage": "Mirage",
  "Hunter Green": "Hunter Green",
  "Big Stone": "Big Stone",
  "Celtic": "Celtic",
  "Timber Green": " Timber Green",
  "Gable Green": "Gable Green",
  "Pine Tree": "Pine Tree",
  "Chathams Blue": "Chathams Blue",
  "Deep Forest Green": "Deep Forest Green",
  "Blumine": "Blumine",
  "Palm Leaf": "Palm Leaf",
  "Nile Blue": "Nile Blue",
  "Fun Blue": "Fun Blue",
  "Lucky Point": "Lucky Point",
  "Mountain Meadow": " Mountain Meadow",
  "Tolopea": "Tolopea",
  "Haiti": "Haiti",
  "Deep Koamaru": "Deep Koamaru",
  "Acadia": "Acadia",
  "Seaweed": "Seaweed",
  "Biscay": "Biscay",
  "Matisse": "Matisse",
  "Crowshead": "Crowshead",
  "Rangoon Green": "Rangoon Green",
  "Persian Blue": "Persian Blue",
  "Everglade": "Everglade",
  "Elm": "Elm",
  "Green Pea": "Green Pea",
  "Creole": "Creole",
  "Karaka": "Karaka",
  "El Paso": "El Paso",
  "Cello": "Cello",
  "Te Papa Green": "Te Papa Green",
  "Dodger Blue": "Dodger Blue",
  "Eastern Blue": "Eastern Blue",
  "Night Rider": "Night Rider",
  "Java": "Java ",
  "Jacksons Purple": "Jacksons Purple",
  "Cloud Burst": "Cloud Burst",
  "Blue Dianne": "Blue Dianne",
  "Eternity": "Eternity",
  "Deep Blue": "Deep Blue",
  "Forest Green": "Forest Green",
  "Mallard": "Mallard",
  "Violet": "Violet",
  "Kilimanjaro": "Kilimanjaro",
  "Log Cabin": "Log Cabin",
  "Black Olive": "Black Olive",
  "Green House": "Green House",
  "Graphite": "Graphite",
  "Cannon Black": "Cannon Black",
  "Port Gore": "Port Gore",
  "Shark": "Shark",
  "Green Kelp": "Green Kelp",
  "Curious Blue": "Curious Blue",
  "Paua": "Paua",
  "Paris M": "Paris M",
  "Wood Bark": "Wood Bark",
  "Gondola": "Gondola",
  "Steel Gray": "Steel Grey",
  "Ebony Clay": "Ebony Clay",
  "Bay of Many": "Bay of Many",
  "Plantation": "Plantation",
  "Eucalyptus": "Eucalyptus",
  "Oil": "Oil",
  "Astronaut": "Astronaut",
  "Mariner": "Mariner",
  "Violent Violet": "Violent Violet",
  "Bastille": "Bastille",
  "Zeus": " Zeus",
  "Charade": "Charade",
  "Jelly Bean": "Jelly Bean",
  "Jungle Green": "Jungle Green",
  "Cherry Pie": "Cherry Pie",
  "Coffee Bean": "Coffee Bean",
  "Baltic Sea": "Mar Báltico",
  "Turtle Green": "Turtle Green",
  "Cerulean Blue": "Cerulean Blue",
  "Sepia Black": "Sepia Black",
  "Valhalla": "Valhalla",
  "Heavy Metal": "Heavy Metal",
  "Blue Gem": "Blue Gem",
  "Revolver": "Revolver",
  "Bleached Cedar": "Bleached Cedar",
  "Lochinvar": "Lochinvar",
  "Mikado": "Mikado",
  "Outer Space": "Outer Space",
  "St Tropez": "St Tropez",
  "Jacaranda": "Jacaranda",
  "Jacko Bean": "Jacko Bean",
  "Rangitoto": "Rangitoto",
  "Rhino": "Rhino",
  "Sea Green": "Sea Green",
  "Scooter": "Scooter",
  "Onion": "Onion",
  "Governor Bay": "Governor Bay",
  "Sapphire": "Sapphire",
  "Spectra": "Spectra",
  "Casal": "Casal",
  "Melanzane": "Melanzane",
  "Cocoa Brown": "Cocoa Brown",
  "Woodrush": "Woodrush",
  "San Juan": "San Juan",
  "Turquoise": "Turquesa",
  "Eclipse": "Eclipse",
  "Pickled Bluewood": "Pickled Bluewood",
  "Azure": "Azure",
  "Calypso": "Calypso",
  "Paradiso": "Paradiso",
  "Persian Indigo": "Persian Indigo",
  "Blackcurrant": "Blackcurrant",
  "Mine Shaft": "Mine Shaft",
  "Stromboli": "Stromboli",
  "Bilbao": "Bilbao",
  "Astral": "Astral",
  "Christalle": "Christalle",
  "Thunder": "Thunder",
  "Shamrock": "Shamrock",
  "Tamarind": "Tamarind",
  "Mardi Gras": "Mardi Gras",
  "Valentino": "Valentino",
  "Jagger": "Jagger",
  "Tuna": "Tuna",
  "Chambray": "Chambray",
  "Martinique": "Martinique",
  "Tuatara": "Tuatara",
  "Waiouru": " Waiouru",
  "Ming": "Ming",
  "La Palma": "La Palma",
  "Chocolate": "Chocolate",
  "Clinker": "Clinker",
  "Brown Tumbleweed": "Brown Tumbleweed",
  "Birch": "Birch",
  "Oracle": "Oracle",
  "Blue Diamond": "Blue Diamond",
  "Grape": "Grape",
  "Dune": "Dune",
  "Oxford Blue": "Oxford Blue",
  "Clover": "Clover",
  "Limed Spruce": "Limed Spruce",
  "Dell": "Dell",
  "Toledo": "Toledo",
  "Sambuca": "Sambuca",
  "Jacarta": "Jacarta",
  "William": "William",
  "Killarney": "Killarney",
  "Keppel": "Keppel",
  "Temptress": "Temptress",
  "Aubergine": "Aubergine",
  "Jon": "Jon",
  "Treehouse": "Treehouse",
  "Amazon": "Amazon",
  "Boston Blue": "Boston Blue",
  "Windsor": "Windsor",
  "Rebel": "Rebel",
  "Meteorite": "Meteorite",
  "Dark Ebony": "Dark Ebony",
  "Camouflage": "Camuflagem",
  "Bright Gray": "Bright Grey",
  "Cape Cod": "Cape Cod",
  "Lunar Green": "Lunar Green",
  "Bean": " Bean",
  "Bistre": "Bistre",
  "Goblin": "Goblin",
  "Kingfisher Daisy": "Kingfisher Daisy",
  "Cedar": "Cedar",
  "English Walnut": "English Walnut",
  "Black Marlin": "Black Marlin",
  "Ship Gray": "Ship Grey",
  "Pelorous": "Pelorous",
  "Bronze": "Bronze",
  "Cola": "Cola",
  "Madras": "Madras",
  "Minsk": "Minsk",
  "Cabbage Pont": "Cabbage Pont",
  "Tom Thumb": "Tom Thumb",
  "Mineral Green": "Mineral Green",
  "Puerto Rico": "Puerto Rico",
  "Harlequin": "Arlequin",
  "Brown Pod": "Brown Pod",
  "Cork": "Cork",
  "Masala": "Masala",
  "Thatch Green": "Thatch Green",
  "Fjord": "Fjord",
  "Viridian": "Viridian",
  "Chateau Green": "Chateau Green",
  "Ripe Plum": "Ripe Plum",
  "Paco": "Paco",
  "Deep Oak": "Deep Oak",
  "Merlin": "Merlin",
  "Gun Powder": "Gun Powder",
  "East Bay": "East Bay",
  "Royal Blue": "Royal Blue",
  "Ocean Green": "Ocean Green",
  "Burnt Maroon": "Burnt Maroon",
  "Lisbon Brown": "Lisbon Brown",
  "Faded Jade": "Faded Jade",
  "Scarlet Gum": "Scarlet Gum",
  "Iroko": "Iroko",
  "Armadillo": "Armadillo",
  "River Bed": "River Bed",
  "Green Leaf": "Green Leaf",
  "Barossa": "Barossa",
  "Morocco Brown": "Morocco Brown",
  "Mako": "Mako",
  "Kelp": " Kelp",
  "San Marino": "San Marino",
  "Picton Blue": "Picton Blue",
  "Loulou": "Loulou",
  "Crater Brown": "Crater Brown",
  "Gray Asparagus": "Gray Asparagus",
  "Steel Blue": "Steel Blue",
  "Rustic Red": "Rustic Red",
  "Bulgarian Rose": "Bulgarian Rose",
  "Clairvoyant": "Clairvoyant",
  "Cocoa Bean": "Cocoa Bean",
  "Woody Brown": "Woody Brown",
  "Taupe": "Taupe",
  "Van Cleef": "Van Cleef",
  "Brown Derby": "Brown Derby",
  "Metallic Bronze": "Bronze Metálico",
  "Verdun Green": "Verdun Green",
  "Blue Bayoux": "Blue Bayoux",
  "Bismark": "Bismark",
  "Bracken": "Bracken",
  "Deep Bronze": "Deep Bronze",
  "Mondo": "Mondo ",
  "Tundora": "Tundora",
  "Gravel": "Gravel",
  "Trout": "Trout",
  "Pigment Indigo": "Pigment Indigo",
  "Nandor": "Nandor",
  "Saddle": "Sela",
  "Abbey": "Abbey",
  "Blackberry": "Blackberry",
  "Cab Sav": "Cab Sav",
  "Indian Tan": "Indian Tan",
  "Cowboy": "Cowboy",
  "Livid Brown": " Livid Brown",
  "Rock": "Rock",
  "Punga": "Punga",
  "Bronzetone": "Bronzetone",
  "Woodland": "Woodland",
  "Mahogany": "Mogno",
  "Bossanova": "Bossanova",
  "Matterhorn": "Matterhorn",
  "Bronze Olive": "Bronze Olive",
  "Mulled Wine": "Vinho quente",
  "Axolotl": "Axolotl",
  "Wedgewood": "Wedgewood",
  "Shakespeare": "Shakespeare",
  "Honey Flower": "Flor de Mel",
  "Daisy Bush": "Arbusto Margarida",
  "Indigo": "Índigo",
  "Fern Green": "Verde Samambaia",
  "Fruit Salad": "Salada de Frutas",
  "Apple": "Maçã",
  "Mortar": "Argamassa",
  "Kashmir Blue": "Azul Caxemira",
  "Cutty Sark": "Cutty Sark",
  "Emerald": "Esmeralda",
  "Emperor": "Emperor",
  "Chalet Green": "Chalet Green",
  "Como": "Como",
  "Smalt Blue": "Smalt Blue",
  "Castro": "Castro",
  "Maroon Oak": "Maroon Oak",
  "Gigas": "Gigas",
  "Voodoo": "Voodoo",
  "Victoria": "Victoria",
  "Hippie Green": "Hippie Green",
  "Heath": "Heath",
  "Judge Gray": "Judge Gray",
  "Fuscous Gray": "Fuscous Grey",
  "Vida Loca": "Vida Loca",
  "Cioccolato": "Cioccolato",
  "Saratoga": "Saratoga",
  "Finlandia": "Finlandia",
  "Havelock Blue": "Havelock Blue",
  "Fountain Blue": "Fountain Blue",
  "Spring Leaves": "Spring Leaves",
  "Saddle Brown": "Saddle Brown",
  "Scarpa Flow": "Scarpa Flow",
  "Cactus": "Cactus",
  "Hippie Blue": "Hippie Blue",
  "Wine Berry": "Wine Berry",
  "Brown Bramble": "Brown Bramble",
  "Congo Brown": "Congo Brown",
  "Millbrook": "Millbrook",
  "Waikawa Gray": "Waikawa Gray",
  "Horizon": "Horizon",
  "Jambalaya": "Jambalaya",
  "Bordeaux": "Bordeaux",
  "Mulberry Wood": "Mulberry Wood",
  "Carnaby Tan": "Carnaby Tan",
  "Comet": "Comet",
  "Redwood": "Redwood",
  "Don Juan": "Don Juan",
  "Chicago": "Chicago",
  "Verdigris": "Verdigris",
  "Dingley": "Dingley",
  "Breaker Bay": "Breaker Bay",
  "Kabul": "Kabul",
  "Hemlock": "Hemlock",
  "Irish Coffee": "Irish Coffee",
  "Mid Gray": "Mid Grey",
  "Shuttle Gray": "Shuttle Grey",
  "Aqua Forest": "Aqua Forest",
  "Tradewind": "Tradewind",
  "Horses Neck": "Horses Neck",
  "Smoky": "Smoky",
  "Corduroy": "Corduroy",
  "Danube": "Danube ",
  "Espresso": "Espresso",
  "Eggplant": "Berinjela",
  "Costa Del Sol": "Costa Del Sol",
  "Glade Green": "Glade Green",
  "Buccaneer": "Buccaneer",
  "Quincy": "Quincy",
  "Butterfly Bush": "Butterfly Bush",
  "West Coast": "West Coast",
  "Finch": "Finch",
  "Patina": "Patina",
  "Fern": "Fern",
  "Blue Violet": "Blue Violet",
  "Dolphin": "Dolphin",
  "Storm Dust": "Storm Dust",
  "Siam": "Siam",
  "Nevada": "Nevada",
  "Cornflower Blue": "Cornflower Blue",
  "Viking": "Viking",
  "Rosewood": "Rosewood",
  "Cherrywood": "Cherrywood",
  "Purple Heart": "Purple Heart",
  "Fern Frond": "Fern Frond",
  "Willow Grove": "Willow Grove",
  "Hoki": "Hoki",
  "Pompadour": "Pompadour",
  "Purple": "Roxo",
  "Tyrian Purple": "Tyrian Purple",
  "Dark Tan": "Dark Tan",
  "Silver Tree": "Silver Tree",
  "Bright Green": "Bright Green",
  "Screamin' Green": "Screamin' Green",
  "Black Rose": "Black Rose",
  "Scampi": "Scampi ",
  "Ironside Gray": "Ironside Grey",
  "Viridian Green": "Viridian Green",
  "Christi": "Christi",
  "Nutmeg Wood Finish": "Nutmeg Wood Finish",
  "Zambezi": "Zambezi",
  "Salt Box": "Salt Box",
  "Tawny Port": "Tawny Port",
  "Finn": "Finn",
  "Scorpion": "Scorpion",
  "Lynch": "Lynch",
  "Spice": "Spice ",
  "Himalaya": "Himalaya",
  "Soya Bean": "Soya Bean",
  "Hairy Heath": "Hairy Heath",
  "Royal Purple": "Royal Purple",
  "Shingle Fawn": "Shingle Fawn",
  "Dorado": "Dorado",
  "Bermuda Gray": "Bermuda Grey",
  "Olive Drab": "Olive Drab",
  "Eminence": "Eminence",
  "Turquoise Blue": "Turquoise Blue",
  "Lonestar": " Lonestar",
  "Pine Cone": "Pine Cone",
  "Dove Gray": "Dove Grey",
  "Juniper": "Juniper",
  "Gothic": "Gothic",
  "Red Oxide": "Red Oxide",
  "Moccaccino": "Moccaccino",
  "Pickled Bean": "Pickled Bean",
  "Dallas": "Dallas",
  "Kokoda": "Kokoda",
  "Pale Sky": "Pale Sky",
  "Cafe Royale": "Cafe Royale",
  "Flint": "Flint",
  "Highland": "Highland",
  "Limeade": "Limeade",
  "Downy": "Downy",
  "Persian Plum": "Persian Plum",
  "Sepia": "Sepia",
  "Antique Bronze": "Bronze Antigo",
  "Ferra": "Ferra",
  "Coffee": "Coffee",
  "Slate Gray": "Slate Grey",
  "Cedar Wood Finish": "Cedar Wood Finish ",
  "Metallic Copper": "Cobre Metálico",
  "Affair": "Affair",
  "Studio": "Studio",
  "Tobacco Brown": "Tobacco Brown",
  "Yellow Metal": "Yellow Metal",
  "Peat": "Peat",
  "Olivetone": "Olivetone",
  "Storm Gray": "Storm Grey",
  "Sirocco": "Sirocco",
  "Aquamarine Blue": "Aquamarine Blue",
  "Venetian Red": "Venetian Red ",
  "Old Copper": "Old Copper",
  "Go Ben": "Go Ben",
  "Raven": "Raven",
  "Seance": "Seance",
  "Raw Umber": "Raw Umber",
  "Kimberly": "Kimberly",
  "Crocodile": "Crocodile",
  "Crete": "Crete",
  "Xanadu": "Xanadu",
  "Spicy Mustard": "Spicy Mustard",
  "Limed Ash": "Limed Ash",
  "Rolling Stone": "Rolling Stone",
  "Blue Smoke": "Blue Smoke",
  "Laurel": "Laurel",
  "Mantis": "Mantis",
  "Russett": "Russett",
  "Deluge": "Deluge",
  "Cosmic": "Cosmic",
  "Blue Marguerite": "Blue Marguerite",
  "Lima": "Lima",
  "Sky Blue": "Sky Blue",
  "Dark Burgundy": "Dark Burgundy",
  "Crown of Thorns": "Coroa de Espinhos",
  "Walnut": "Nogueira",
  "Pablo": "Pablo",
  "Pacifika": "Pacifika",
  "Oxley": "Oxley",
  "Pastel Green": "Pastel Verde",
  "Japanese Maple": "Japanese Maple",
  "Mocha": "Mocha",
  "Peanut": "Amendoim",
  "Camouflage Green": "Camuflagem Verde",
  "Wasabi": "Wasabi",
  "Ship Cove": " Ship Cove",
  "Sea Nymph": "Sea Nymph",
  "Roman Coffee": "Roman Coffee",
  "Old Lavender": "Old Lavender",
  "Rum": "Rum",
  "Fedora": "Fedora",
  "Sandstone": "Sandstone",
  "Spray": "Spray",
  "Siren": "Siren",
  "Fuchsia Blue": "Fuchsia Blue",
  "Boulder": "Boulder",
  "Wild Blue Yonder": "Wild Blue Yonder",
  "De York": "De York",
  "Red Beech": "Red Beech",
  "Cinnamon": "Cinnamon",
  "Yukon Gold": "Yukon Gold",
  "Tapa": "Tapa",
  "Waterloo": "Waterloo",
  "Flax Smoke": "Flax Smoke",
  "Amulet": "Amulet",
  "Asparagus": "Asparagus",
  "Kenyan Copper": "Kenyan Copper",
  "Pesto": " Pesto",
  "Topaz": "Topaz",
  "Concord": "Concord",
  "Jumbo": "Jumbo",
  "Trendy Green": "Trendy Green",
  "Gumbo": "Gumbo",
  "Acapulco": "Acapulco",
  "Neptune": "Netuno",
  "Pueblo": "Pueblo",
  "Bay Leaf": "Bay Leaf",
  "Malibu": "Malibu",
  "Bermuda": "Bermuda",
  "Copper Canyon": " Copper Canyon",
  "Claret": "Claret",
  "Peru Tan": "Peru Tan",
  "Falcon": "Falcon",
  "Mobster": "Mobster",
  "Moody Blue": "Moody Blue",
  "Chartreuse": "Chartreuse",
  "Aquamarine": "Aquamarine",
  "Maroon": "Maroon",
  "Rose Bud Cherry": "Rose Bud Cherry",
  "Falu Red": "Falu Red",
  "Red Robin": " Red Robin",
  "Vivid Violet": "Vivid Violet",
  "Russet": "Russet",
  "Friar Gray": "Frei Gray",
  "Olive": "Olive",
  "Gray": "Gray",
  "Gulf Stream": "Gulf Stream",
  "Glacier": "Glacier",
  "Seagull": "Seagull",
  "Nutmeg": "Nutmeg",
  "Spicy Pink": "Spicy Pink",
  "Empress": "Empress ",
  "Spanish Green": "Spanish Green",
  "Sand Dune": "Sand Dune",
  "Gunsmoke": "Gunsmoke",
  "Battleship Gray": "Battleship Gray",
  "Merlot": "Merlot",
  "Shadow": "Shadow",
  "Chelsea Cucumber": "Chelsea Pepino",
  "Monte Carlo": "Monte Carlo",
  "Plum": "Plum",
  "Granny Smith": "Granny Smith",
  "Chetwode Blue": "Chetwode Blue",
  "Bandicoot": "Bandicoot",
  "Bali Hai": "Bali Hai",
  "Half Baked": "Half Baked",
  "Red Devil": "Red Devil",
  "Lotus": "Lotus",
  "Ironstone": "Ironstone",
  "Bull Shot": "Bull Shot",
  "Rusty Nail": "Rusty Nail",
  "Bitter": "Bitter",
  "Regent Gray": "Regent Gray",
  "Disco": " Disco",
  "Americano": "Americano",
  "Hurricane": "Hurricane",
  "Oslo Gray": "Oslo Gray",
  "Sushi": "Sushi",
  "Spicy Mix": "Spicy Mix",
  "Kumera": "Kumera",
  "Suva Gray": "Suva Gray",
  "Avocado": "Avocado",
  "Camelot": "Camelot",
  "Solid Pink": "Solid Pink",
  "Cannon Pink": "Cannon Pink ",
  "Makara": "Makara",
  "Burnt Umber": "Burnt Umber",
  "True V": "True V",
  "Clay Creek": "Clay Creek",
  "Monsoon": "Monsoon",
  "Stack": "Stack",
  "Jordy Blue": "Jordy Blue",
  "Electric Violet": "Electric Violet",
  "Monarch": "Monarch",
  "Corn Harvest": "Corn Harvest",
  "Olive Haze": "Olive Haze",
  "Schooner": "Schooner",
  "Natural Gray": "Natural Grey",
  "Mantle": "Mantle",
  "Portage": "Portage",
  "Envy": "Envy",
  "Cascade": "Cascade",
  "Riptide": "Riptide",
  "Cardinal Pink": "Cardinal Pink",
  "Mule Fawn": "Mule Fawn",
  "Potters Clay": "Potters Clay",
  "Trendy Pink": "Trendy Pink ",
  "Paprika": "Paprika",
  "Sanguine Brown": "Sanguine Brown",
  "Tosca": "Tosca",
  "Cement": "Cement",
  "Granite Green": "Granite Green",
  "Manatee": "Manatee",
  "Polo Blue": "Polo Blue",
  "Red Berry": "Red Berry",
  "Rope": "Rope",
  "Opium": "Opium",
  "Domino": "Domino",
  "Mamba": "Mamba",
  "Nepal": "Nepal",
  "Pohutukawa": "Pohutukawa",
  "El Salva": "El Salva",
  "Korma": "Korma",
  "Squirrel": "Squirrel",
  "Vista Blue": "Vista Blue",
  "Burgundy": "Burgundy",
  "Old Brick": "Old Brick",
  "Hemp": "Hemp",
  "Almond Frost": "Almond Frost",
  "Sycamore": "Sycamore ",
  "Sangria": "Sangria",
  "Cumin": "Cominho",
  "Beaver": "Castor",
  "Stonewall": "Stonewall",
  "Venus": "Vênus",
  "Medium Purple": "Roxo Médio",
  "Cornflower": "Centáurea",
  "Algae Green": "Algas Verdes",
  "Copper Rust": "Cobre Ferrugem",
  "Arrowtown": "Arrowtown",
  "Scarlett": "Scarlett",
  "Strikemaster": " Strikemaster",
  "Mountain Mist": "Mountain Mist",
  "Carmine": "Carmine",
  "Brown": "Brown",
  "Leather": "Couro",
  "Purple Mountain": "Purple Mountain",
  "Lavender Purple": "Lavender Purple",
  "Pewter": "Pewter",
  "Summer Green": "Summer Green",
  "Au Chico": "Au Chico",
  "Wisteria": "Wisteria",
  "Atlantis": "Atlantis ",
  "Vin Rouge": "Vin Rouge",
  "Lilac Bush": "Lilac Bush",
  "Bazaar": "Bazaar",
  "Hacienda": "Hacienda",
  "Pale Oyster": "Pale Oyster",
  "Mint Green": "Mint Green",
  "Fresh Eggplant": "Fresh Berinjela",
  "Violet Eggplant": "Violet Berinjela",
  "Tamarillo": "Tamarillo",
  "Totem Pole": "Totem Pole",
  "Copper Rose": " Copper Rose",
  "Amethyst": "Amethyst",
  "Mountbatten Pink": "Mountbatten Pink",
  "Blue Bell": "Blue Bell",
  "Prairie Sand": "Prairie Sand",
  "Toast": "Toast",
  "Gurkha": "Gurkha",
  "Olivine": "Olivine",
  "Shadow Green": "Shadow Green",
  "Oregon": "Oregon",
  "Lemon Grass": "Lemon Grass",
  "Stiletto": " Stiletto",
  "Hawaiian Tan": "Hawaiian Tan",
  "Gull Gray": "Gull Grey",
  "Pistachio": "Pistachio",
  "Granny Smith Apple": "Granny Smith Apple",
  "Anakiwa": "Anakiwa",
  "Chelsea Gem": "Chelsea Gem",
  "Sepia Skin": "Sepia Skin",
  "Sage": "Sage",
  "Citron": "Citron",
  "Rock Blue": "Rock Blue",
  "Morning Glory": "Morning Glory",
  "Cognac": "Cognac",
  "Reef Gold": "Reef Gold",
  "Star Dust": "Star Dust",
  "Santas Gray": "Santas Grey",
  "Sinbad": "Sinbad",
  "Feijoa": "Feijoa",
  "Tabasco": "Tabasco",
  "Buttered Rum": "Buttered Rum",
  "Hit Gray": "Hit Gray",
  "Citrus": "Citrus",
  "Aqua Island": "Aqua Island",
  "Water Leaf": "Water Leaf",
  "Flirt": "Flirt",
  "Rouge": "Rouge",
  "Cape Palliser": "Cape Palliser",
  "Gray Chateau": "Gray Chateau",
  "Edward": "Edward",
  "Pharlap": "Pharlap",
  "Amethyst Smoke": "Amethyst Smoke",
  "Blizzard Blue": "Blizzard Blue",
  "Delta": "Delta",
  "Wistful": "Wistful",
  "Green Smoke": "Green Smoke",
  "Jazzberry Jam": "Jazzberry Jam",
  "Zorba": "Zorba",
  "Bahia": "Bahia",
  "Roof Terracotta": "Roof Terracotta",
  "Paarl": "Paarl",
  "Barley Corn": "Barley Corn",
  "Donkey Brown": "Donkey Brown",
  "Dawn": "Dawn",
  "Mexican Red": "Mexican Red",
  "Luxor Gold": "Luxor Gold",
  "Rich Gold": "Rich Gold",
  "Reno Sand": "Reno Sand",
  "Coral Tree": "Coral Tree",
  "Dusty Gray": "Dusty Grey",
  "Dull Lavender": "Dull Lavender",
  "Tallow": "Tallow",
  "Bud": "Bud",
  "Locust": "Locust",
  "Norway": "Norway",
  "Chinook": "Chinook",
  "Gray Olive": "Azeitona Cinza",
  "Aluminium": "Alumínio",
  "Cadet Blue": "Azul Cadete",
  "Schist": "Xisto",
  "Tower Gray": "Torre Cinza",
  "Perano": "Perano",
  "Opal": "Opal",
  "Night Shadz": "Night Shadz",
  "Fire": "Fogo",
  "Muesli": "Muesli",
  "Sandal": "Sandália",
  "Shady Lady": "Shady Lady",
  "Logan": "Logan",
  "Spun Pearl": "Spun Pearl",
  "Regent St Blue": "Regent St Blue",
  "Magic Mint": "Magic Mint",
  "Lipstick": "Batom",
  "Royal Heath": "Royal Heath",
  "Sandrift": "Sandrift",
  "Cold Purple": "Cold Purple",
  "Bronco": "Bronco",
  "Limed Oak": "Limed Oak",
  "East Side": "East Side",
  "Lemon Ginger": "Lemon Ginger",
  "Napa": "Napa",
  "Hillary": "Hillary",
  "Cloudy": "Cloudy",
  "Silver Chalice": "Silver Chalice",
  "Swamp Green": "Swamp Green",
  "Spring Rain": "Spring Rain",
  "Conifer": "Conifer",
  "Celadon": "Celadon",
  "Mandalay": "Mandalay",
  "Casper": " Casper",
  "Moss Green": "Moss Green",
  "Padua": "Padua",
  "Green Yellow": "Green Yellow",
  "Hippie Pink": "Hippie Pink",
  "Desert": "Desert",
  "Bouquet": "Bouquet",
  "Medium Carmine": "Medium Carmine",
  "Apple Blossom": "Apple Blossom",
  "Brown Rust": "Brown Rust",
  "Driftwood": "Driftwood",
  "Alpine": " Alpine",
  "Lucky": "Lucky",
  "Martini": "Martini",
  "Bombay": "Bombaim",
  "Pigeon Post": "Pigeon Post",
  "Cadillac": "Cadillac",
  "Matrix": "Matrix",
  "Tapestry": "Tapestry",
  "Mai Tai": "Mai Tai",
  "Del Rio": "Del Rio",
  "Powder Blue": "Powder Blue",
  "Inch Worm": "Inch Worm",
  "Bright Red": "Bright Red",
  "Vesuvius": "Vesuvius",
  "Pumpkin Skin": "Pumpkin Skin ",
  "Santa Fe": "Santa Fe",
  "Teak": "Teak",
  "Fringy Flower": "Fringy Flower",
  "Ice Cold": "Ice Cold",
  "Shiraz": "Shiraz",
  "Biloba Flower": "Biloba Flower",
  "Tall Poppy": "Tall Poppy",
  "Fiery Orange": "Fiery Orange",
  "Hot Toddy": "Hot Toddy",
  "Taupe Gray": "Taupe Grey",
  "La Rioja": "La Rioja",
  "Well Read": "Well Read",
  "Blush": "Blush",
  "Jungle Mist": "Jungle Mist",
  "Turkish Rose": "Turkish Rose",
  "Lavender": "Lavender",
  "Mongoose": "Mongoose",
  "Olive Green": "Olive Green",
  "Jet Stream": "Jet Stream",
  "Cruise": "Cruise",
  "Hibiscus": "Hibiscus",
  "Thatch": "Thatch",
  "Heathered Gray": "Heathered Grey",
  "Eagle": "Eagle",
  "Spindle": "Spindle",
  "Gum Leaf": "Gum Leaf",
  "Rust": "Rust",
  "Muddy Waters": "Muddy Waters",
  "Sahara": "Sahara",
  "Husk": "Husk",
  "Nobel": "Nobel",
  "Heather": "Heather",
  "Madang": "Madang",
  "Milano Red": "Milano Red",
  "Copper": "Copper",
  "Gimblet": "Gimblet",
  "Green Spring": "Green Spring",
  "Celery": "Celery",
  "Sail": "Sail",
  "Chestnut": "Chestnut",
  "Crail": "Crail",
  "Marigold": "Marigold",
  "Wild Willow": "Wild Willow",
  "Rainee": "Rainee",
  "Guardsman Red": "Guardsman Vermelho",
  "Rock Spray": "Rock Spray",
  "Bourbon": "Bourbon",
  "Pirate Gold": "Pirate Gold",
  "Nomad": "Nomad",
  "Submarine": "Submarine",
  "Charlotte": "Charlotte",
  "Medium Red Violet": "Medium Red Violet",
  "Brandy Rose": "Brandy Rose",
  "Rio Grande": "Rio Grande",
  "Surf": "Surf",
  "Powder Ash": " Powder Ash",
  "Tuscany": "Toscana",
  "Quicksand": "Areia movediça",
  "Silk": "Seda",
  "Malta": "Malta",
  "Chatelle": "Chatelle",
  "Lavender Gray": "Lavender Grey",
  "French Gray": "French Gray",
  "Clay Ash": "Clay Ash",
  "Loblolly": "Loblolly",
  "French Pass": "French Pass",
  "London Hue": "London Hue",
  "Pink Swan": "Pink Swan",
  "Fuego": "Fuego",
  "Rose of Sharon": "Rose of Sharon",
  "Tide": "Tide",
  "Blue Haze": "Blue Haze",
  "Silver Sand": "Silver Sand",
  "Key Lime Pie": "Key Lime Pie",
  "Ziggurat": "Ziggurat",
  "Lime": "Lime",
  "Thunderbird": "Thunderbird",
  "Mojo": "Mojo",
  "Old Rose": "Old Rose",
  "Silver": "Silver",
  "Pale Leaf": "Pale Leaf",
  "Pixie Green": "Pixie Green",
  "Tia Maria": "Tia Maria",
  "Fuchsia Pink": "Fuchsia Pink",
  "Buddha Gold": "Buddha Gold",
  "Bison Hide": "Bison Hide",
  "Tea": "Tea",
  "Gray Suit": "Gray Suit ",
  "Sprout": "Sprout",
  "Sulu": "Sulu",
  "Indochine": "Indochine",
  "Twine": "Twine",
  "Cotton Seed": "Cotton Seed",
  "Pumice": "Pumice",
  "Jagged Ice": "Jagged Ice",
  "Maroon Flush": "Maroon Flush",
  "Indian Khaki": "Indian Khaki",
  "Pale Slate": "Pale Slate",
  "Gray Nickel": "Gray Nickel ",
  "Periwinkle Gray": "Periwinkle Grey",
  "Tiara": "Tiara",
  "Tropical Blue": "Tropical Blue",
  "Cardinal": "Cardinal",
  "Fuzzy Wuzzy Brown": "Fuzzy Wuzzy Brown",
  "Orange Roughy": "Orange Roughy",
  "Mist Gray": "Mist Grey",
  "Coriander": "Coentro",
  "Mint Tulip": "Mint Tulip",
  "Mulberry": "Mulberry",
  "Nugget": " Nugget",
  "Tussock": "Tussock",
  "Sea Mist": "Sea Mist",
  "Yellow Green": "Yellow Green",
  "Brick Red": "Brick Red",
  "Contessa": "Contessa",
  "Oriental Pink": "Oriental Pink",
  "Roti": "Roti",
  "Ash": "Ash",
  "Kangaroo": "Kangaroo",
  "Las Palmas": "Las Palmas",
  "Monza": "Monza ",
  "Red Violet": "Red Violet",
  "Coral Reef": "Coral Reef",
  "Melrose": "Melrose",
  "Cloud": "Cloud",
  "Ghost": "Ghost",
  "Pine Glade": "Pine Glade",
  "Botticelli": "Botticelli",
  "Antique Brass": "Antique Brass",
  "Lilac": "Lilac",
  "Hokey Pokey": "Hokey Pokey",
  "Lily": "Lily",
  "Laser": "Laser",
  "Edgewater": "Edgewater",
  "Piper": "Piper",
  "Pizza": "Pizza",
  "Light Wisteria": "Light Wisteria",
  "Rodeo Dust": "Rodeo Dust",
  "Sundance": "Sundance",
  "Earls Green": "Earls Green",
  "Silver Rust": "Silver Rust",
  "Conch": "Conch",
  "Reef": "Reef",
  "Aero Blue": " Aero Blue",
  "Flush Mahogany": "Flush Mahogany",
  "Turmeric": "Turmeric",
  "Paris White": "Paris White",
  "Bitter Lemon": "Bitter Lemon",
  "Skeptic": "Skeptic",
  "Viola": "Viola",
  "Foggy Gray": "Foggy Gray",
  "Green Mist": "Green Mist",
  "Nebula": "Nebula",
  "Persian Red": "Persian Red",
  "Burnt Orange": "Burnt Orange",
  "Ochre": "Ochre",
  "Puce": "Puce",
  "Thistle Green": "Thistle Green",
  "Periwinkle": "Periwinkle",
  "Electric Lime": "Electric Lime",
  "Tenn": "Tenn",
  "Chestnut Rose": "Chestnut Rose",
  "Brandy Punch": "Brandy Punch",
  "Onahau": "Onahau",
  "Sorrell Brown": "Sorrell Brown",
  "Cold Turkey": "Cold Turkey",
  "Yuma": "Yuma",
  "Chino": "Chino",
  "Eunry": "Eunry",
  "Old Gold": "Old Gold",
  "Tasman": "Tasman",
  "Surf Crest": "Surf Crest",
  "Humming Bird": "Humming Bird",
  "Scandal": "Scandal",
  "Red Stage": "Red Stage",
  "Hopbush": "Hopbush",
  "Meteor": " Meteor",
  "Perfume": "Perfume",
  "Prelude": "Prelude",
  "Tea Green": "Tea Green",
  "Geebung": "Geebung",
  "Vanilla": "Vanilla",
  "Soft Amber": "Soft Amber",
  "Celeste": "Celeste",
  "Mischka": "Mischka",
  "Pear": "Pear",
  "Hot Cinnamon": "Hot Canela",
  "Raw Sienna": "Raw Sienna",
  "Careys Pink": "Careys Pink",
  "Tan": "Tan",
  "Deco": "Deco",
  "Blue Romance": "Blue Romance",
  "Gossip": "Gossip",
  "Sisal": "Sisal",
  "Swirl": "Swirl",
  "Charm": "Charm",
  "Clam Shell": "Clam Shell",
  "Straw": "Straw",
  "Akaroa": "Akaroa",
  "Bird Flower": "Bird Flower",
  "Iron": "Iron",
  "Geyser": "Geyser",
  "Hawkes Blue": "Hawkes Blue",
  "Grenadier": "Grenadier",
  "Can Can": "Can Can",
  "Whiskey": "Whiskey",
  "Winter Hazel": "Winter Hazel",
  "Granny Apple": "Granny Apple",
  "My Pink": "My Pink",
  "Tacha": "Tacha",
  "Moon Raker": "Moon Raker",
  "Quill Gray": "Quill Gray",
  "Snowy Mint": "Snowy Mint",
  "New York Pink": "New York Pink",
  "Pavlova": "Pavlova",
  "Fog": "Fog",
  "Valencia": "Valencia",
  "Japonica": "Japonica",
  "Thistle": "Thistle",
  "Maverick": "Maverick",
  "Foam": "Foam",
  "Cabaret": "Cabaret",
  "Burning Sand": "Areia Ardente",
  "Cameo": "Cameo",
  "Timberwolf": "Timberwolf",
  "Tana": "Tana",
  "Link Water": "Link Water",
  "Mabel": "Mabel",
  "Cerise": "Cerise",
  "Flame Pea": "Flame Pea",
  "Bamboo": "Bambu",
  "Red Damask": "Red Damask",
  "Orchid": "Orchid",
  "Copperfield": " Copperfield",
  "Golden Grass": "Golden Grass",
  "Zanah": "Zanah",
  "Iceberg": "Iceberg",
  "Oyster Bay": "Oyster Bay",
  "Cranberry": "Cranberry",
  "Petite Orchid": "Petite Orchid",
  "Di Serria": "Di Serria",
  "Alto": "Alto",
  "Frosted Mint": "Frosted Mint",
  "Crimson": "Crimson",
  "Punch": "Punch ",
  "Galliano": "Galliano",
  "Blossom": "Blossom",
  "Wattle": "Wattle",
  "Westar": "Westar",
  "Moon Mist": "Moon Mist",
  "Caper": "Caper",
  "Swans Down": "Swans Down",
  "Swiss Coffee": "Swiss Coffee",
  "White Ice": "White Ice",
  "Cerise Red": "Cerise Red",
  "Roman": "Roman",
  "Tumbleweed": "Tumbleweed",
  "Gold Tips": "Gold Tips",
  "Brandy": "Brandy",
  "Wafer": "Wafer",
  "Sapling": "Sapling",
  "Barberry": "Barberry",
  "Beryl Green": "Beryl Green",
  "Pattens Blue": "Pattens Blue",
  "Heliotrope": "Heliotrope",
  "Apache": "Apache",
  "Chenin": "Chenin",
  "Lola": "Lola ",
  "Willow Brook": "Willow Brook",
  "Chartreuse Yellow": "Chartreuse Yellow",
  "Mauve": "Mauve",
  "Anzac": "Anzac",
  "Harvest Gold": "Harvest Gold",
  "Calico": "Calico",
  "Baby Blue": "Baby Blue",
  "Sunglo": "Sunglo",
  "Equator": "Equator",
  "Pink Flare": "Pink Flare",
  "Periglacial Blue": "Periglacial Blue ",
  "Kidnapper": "Sequestrador",
  "Tara": "Tara",
  "Mandy": "Mandy",
  "Terracotta": "Terracota",
  "Golden Bell": "Golden Bell",
  "Shocking": "Shocking",
  "Dixie": "Dixie",
  "Light Orchid": "Light Orchid",
  "Snuff": "Snuff",
  "Mystic": "Mystic",
  "Apple Green": "Apple Green",
  "Razzmatazz": " Razzmatazz",
  "Alizarin Crimson": "Alizarin Crimson",
  "Cinnabar": "Cinnabar",
  "Cavern Pink": "Cavern Pink",
  "Peppermint": "Peppermint",
  "Mindaro": "Mindaro",
  "Deep Blush": "Deep Blush",
  "Gamboge": "Gamboge",
  "Melanie": "Melanie",
  "Twilight": "Crepúsculo",
  "Bone": "Bone",
  "Sunflower": "Girassol",
  "Grain Brown": "Grain Brown",
  "Zombie": "Zumbi",
  "Frostee": "Frostee",
  "Snow Flurry": "Snow Flurry",
  "Amaranth": "Amaranth",
  "Zest": "Zest",
  "Dust Storm": "Dust Storm",
  "Stark White": "Stark White",
  "Hampton": "Hampton",
  "Bon Jour": "Bon Jour",
  "Mercury": "Mercury",
  "Polar": " Polar",
  "Trinidad": "Trinidad",
  "Gold Sand": "Gold Sand",
  "Cashmere": "Cashmere",
  "Double Spanish White": "Double Spanish White",
  "Satin Linen": "Satin Linen",
  "Harp": "Harp",
  "Off Green": "Off Green",
  "Hint of Green": "Hint of Green",
  "Tranquil": "Tranquil",
  "Mango Tango": "Mango Tango",
  "Christine": "Christine",
  "Tony's Pink": "Tony's Pink",
  "Kobi": "Kobi",
  "Rose Fog": "Rose Fog",
  "Corn": "Corn",
  "Putty": "Putty",
  "Gray Nurse": "Gray Nurse",
  "Lily White": "Lily White",
  "Bubbles": "Bubbles",
  "Fire Bush": "Fire Bush",
  "Shilo": "Shilo",
  "Pearl Bush": "Pearl Bush",
  "Green White": "Green White",
  "Chrome White": "Chrome White",
  "Gin": "Gin",
  "Aqua Squeeze": "Aqua Squeeze",
  "Clementine": "Clementine",
  "Burnt Sienna": "Burnt Sienna",
  "Tahiti Gold": "Tahiti Gold",
  "Oyster Pink": "Oyster Pink",
  "Confetti": "Confetti",
  "Ebb": "Ebb",
  "Ottoman": "Ottoman",
  "Clear Day": "Clear Day",
  "Carissma": "Carissma",
  "Porsche": "Porsche",
  "Tulip Tree": "Tulip Tree",
  "Rob Roy": "Rob Roy",
  "Raffia": "Raffia",
  "White Rock": "White Rock",
  "Panache": "Panache",
  "Solitude": "Solitude",
  "Aqua Spring": "Aqua Spring",
  "Dew": "Dew",
  "Apricot": "Apricot",
  "Zinnwaldite": "Zinnwaldite",
  "Fuel Yellow": "Fuel Yellow",
  "Ronchi": "Ronchi",
  "French Lilac": "French Lilac",
  "Just Right": "Just Right",
  "Wild Rice": "Wild Rice",
  "Fall Green": "Fall Green",
  "Aths Special": "Aths Special",
  "Starship": "Starship",
  "Red Ribbon": "Red Ribbon",
  "Tango": "Tango",
  "Carrot Orange": "Cenoura Laranja",
  "Sea Pink": "Sea Pink",
  "Tacao": "Tacao",
  "Desert Sand": "Desert Sand",
  "Pancho": "Pancho",
  "Chamois": "Chamois",
  "Primrose": "Primrose",
  "Frost": "Frost",
  "Aqua Haze": "Aqua Haze",
  "Zumthor": " Zumthor",
  "Narvik": "Narvik",
  "Honeysuckle": "Honeysuckle",
  "Lavender Magenta": "Lavender Magenta",
  "Beauty Bush": "Beauty Bush",
  "Chalky": "Chalky",
  "Almond": "Almond",
  "Flax": "Linho",
  "Bizarre": "Bizarre",
  "Double Colonial White": "Double Colonial White",
  "Cararra": "Cararra",
  "Manz": "Manz",
  "Tahuna Sands": "Tahuna Sands",
  "Athens Gray": "Athens Grey",
  "Tusk": "Tusk",
  "Loafer": "Loafer",
  "Catskill White": "Catskill White",
  "Twilight Blue": "Twilight Blue",
  "Jonquil": "Jonquil",
  "Rice Flower": "Rice Flower",
  "Jaffa": "Jaffa",
  "Gallery": "Gallery",
  "Porcelain": "Porcelain",
  "Mauvelous": "Mauvelous",
  "Golden Dream": "Golden Dream",
  "Golden Sand": "Golden Sand",
  "Buff": "Buff",
  "Prim": "Prim",
  "Khaki": "Khaki",
  "Selago": "Selago",
  "Titan White": "Titan White",
  "Alice Blue": "Alice Blue",
  "Feta": "Feta",
  "Gold Drop": "Gold Drop",
  "Wewak": " Wewak",
  "Sahara Sand": "Sahara Sand",
  "Parchment": "Pergaminho",
  "Blue Chalk": "Blue Chalk",
  "Mint Julep": "Mint Julep",
  "Seashell": "Seashell",
  "Saltpan": "Salan",
  "Tidal": "Tidal",
  "Chiffon": "Chiffon",
  "Flamingo": "Flamingo",
  "Tangerine": "Tangerine",
  "Mandy's Pink": "Mandy's Pink",
  "Concrete": "Concreto",
  "Black Squeeze": "Black Squeeze",
  "Pomegranate": "Romã",
  "Buttercup": "Buttercup",
  "New Orleans": "New Orleans",
  "Vanilla Ice": "Vanilla Ice",
  "Sidecar": "Sidecar",
  "Dawn Pink": "Dawn Pink",
  "Wheatfield": "Wheatfield",
  "Canary": "Canary",
  "Orinoco": "Orinoco",
  "Carla": "Carla",
  "Hollywood Cerise": " Hollywood Cerise",
  "Sandy brown": "Sandy brown",
  "Saffron": "Saffron",
  "Ripe Lemon": "Ripe Lemon",
  "Janna": "Janna",
  "Pampas": "Pampas",
  "Wild Sand": "Wild Sand",
  "Zircon": "Zircon",
  "Froly": "Froly",
  "Cream Can": "Cream Can",
  "Manhattan": "Manhattan",
  "Maize": "Maize ",
  "Wheat": "Wheat",
  "Sandwisp": "Sandwisp",
  "Pot Pourri": "Pot Pourri",
  "Albescent White": "Albescent White",
  "Soft Peach": "Soft Peach",
  "Ecru White": "Ecru White",
  "Beige": "Beige",
  "Golden Fizz": "Golden Fizz",
  "Australian Mint": "Australian Mint",
  "French Rose": "French Rose",
  "Brilliant Rose": " Brilliant Rose",
  "Illusion": "Illusion",
  "Merino": "Merino",
  "Black Haze": "Black Haze",
  "Spring Sun": "Spring Sun",
  "Violet Red": "Violet Red",
  "Chilean Fire": "Chilean Fire",
  "Persian Pink": "Persian Pink",
  "Rajah": "Rajah",
  "Azalea": "Azalea",
  "We Peep": "We Peep",
  "Quarter Spanish White": "Quarter Spanish White",
  "Whisper": "Whisper",
  "Snow Drift": "Snow Drift",
  "Casablanca": "Casablanca",
  "Chantilly": "Chantilly",
  "Cherub": "Cherub",
  "Marzipan": "Marzipan",
  "Energy Yellow": "Energy Yellow",
  "Givry": "Givry",
  "White Linen": "White Linen",
  "Magnolia": "Magnolia",
  "Spring Wood": " Spring Wood",
  "Coconut Cream": "Coconut Cream",
  "White Lilac": "White Lilac",
  "Desert Storm": "Desert Storm",
  "Texas": "Texas",
  "Corn Field": "Corn Field",
  "Mimosa": "Mimosa",
  "Carnation": "Cravo",
  "Saffron Mango": "Saffron Mango",
  "Carousel Pink": "Carousel Pink",
  "Dairy Cream": "Dairy Cream",
  "Portica": "Portica",
  "Amour": "Amour",
  "Rum Swizzle": "Rum Swizzle",
  "Dolly": "Dolly",
  "Sugar Cane": "Sugar Cane",
  "Ecstasy": "Ecstasy",
  "Tan Hide": "Tan Hide",
  "Corvette": "Corvette",
  "Peach Yellow": "Peach Yellow",
  "Turbo": "Turbo",
  "Astra": "Astra",
  "Champagne": " Champagne",
  "Linen": "Linen",
  "Fantasy": "Fantasy",
  "Citrine White": "Citrine White",
  "Alabaster": "Alabaster",
  "Hint of Yellow": "Hint of Yellow",
  "Milan": "Milan",
  "Brink Pink": "Brink Pink",
  "Geraldine": "Geraldine",
  "Lavender Rose": "Lavender Rose",
  "Sea Buckthorn": "Sea Buckthorn",
  "Sun": " Sun",
  "Lavender Pink": "Lavender Pink",
  "Rose Bud": "Rose Bud",
  "Cupid": "Cupid",
  "Classic Rose": "Classic Rose",
  "Apricot Peach": "Apricot Peach",
  "Banana Mania": "Banana Mania",
  "Marigold Yellow": "Marigold Yellow",
  "Festival": "Festival",
  "Sweet Corn": "Sweet Corn",
  "Candy Corn": "Candy Corn",
  "Hint of Red": "Hint of Red",
  "Shalimar": "Shalimar",
  "Shocking Pink": "Shocking Pink",
  "Tickle Me Pink": "Tickle Me Pink",
  "Tree Poppy": "Tree Poppy",
  "Lightning Yellow": "Lightning Yellow",
  "Goldenrod": "Goldenrod",
  "Candlelight": "Candlelight",
  "Cherokee": "Cherokee",
  "Double Pearl Lusta": "Double Pearl Lusta",
  "Pearl Lusta": "Pearl Lusta",
  "Vista White": "Vista White",
  "Bianca": "Bianca",
  "Moon Glow": "Moon Glow",
  "China Ivory": "China Ivory",
  "Ceramic": "Ceramic",
  "Torch Red": "Torch Red",
  "Wild Watermelon": "Wild Watermelon",
  "Crusta": "Crusta",
  "Sorbus": "Sorbus",
  "Sweet Pink": "Sweet Pink",
  "Light Apricot": "Light Apricot",
  "Pig Pink": "Pig Pink",
  "Cinderella": "Cinderela",
  "Golden Glow": "Golden Glow",
  "Lemon": "Lemon",
  "Old Lace": "Old Lace",
  "Half Colonial White": "Half Colonial White",
  "Drover": "Drover",
  "Pale Prim": "Pale Prim",
  "Cumulus": "Cumulus",
  "Persian Rose": "Persian Rose",
  "Sunset Orange": "Sunset Orange",
  "Bittersweet": "Bittersweet",
  "California": "Califórnia",
  "Yellow Sea": "Yellow Sea",
  "Melon": "Melon",
  "Bright Sun": "Bright Sun",
  "Dandelion": "Dandelion",
  "Salomie": "Salomie",
  "Cape Honey": "Cape Honey",
  "Remy": "Remy",
  "Oasis": "Oasis",
  "Bridesmaid": "Dama de honra",
  "Beeswax": "Cera de abelha",
  "Bleach White": "Bleach White",
  "Pipi": "Pipi",
  "Half Spanish White": "Half Spanish White",
  "Wisp Pink": "Wisp Pink",
  "Provincial Pink": "Provincial Pink",
  "Half Dutch White": "Half Dutch White",
  "Solitaire": "Solitaire",
  "White Pointer": "White Pointer",
  "Off Yellow": " Off Yellow",
  "Orange White": "Orange White",
  "Red": "Red",
  "Rose": "Rose",
  "Purple Pizzazz": "Purple Pizzazz",
  "Magenta/ Fuchsia": "Magenta/ Fuchsia",
  "Scarlet": "Scarlet",
  "Wild Strawberry": "Wild Strawberry",
  "Razzle Dazzle Rose": "Razzle Dazzle Rose",
  "Radical Red": "Radical Red",
  "Red Orange": "Laranja Vermelho",
  "Coral Red": "Coral Red",
  "Vermilion": "Vermilion",
  "International Orange": "International Orange",
  "Outrageous Orange": "Outrageous Orange",
  "Blaze Orange": "Blaze Orange",
  "Pink Flamingo": "Pink Flamingo",
  "Orange": "Orange",
  "Hot Pink": "Hot Pink",
  "Persimmon": "Caqui",
  "Blush Pink": "Blush Pink",
  "Burning Orange": "Burning Orange",
  "Pumpkin": "Pumpkin",
  "Flamenco": "Flamenco",
  "Flush Orange": "Flush Orange",
  "Coral": "Coral",
  "Salmon": "Salmon",
  "Pizazz": "Pizazz",
  "West Side": "West Side",
  "Pink Salmon": "Pink Salmon",
  "Neon Carrot": "Neon Carrot",
  "Atomic Tangerine": "Atomic Tangerine",
  "Vivid Tangerine": "Vivid Tangerine",
  "Sunshade": "Sunshade",
  "Orange Peel": "Orange Peel",
  "Mona Lisa": "Mona Lisa",
  "Web Orange": "Web Orange",
  "Carnation Pink": "Cravo Pink",
  "Hit Pink": "Hit Pink",
  "Yellow Orange": "Yellow Orange",
  "Cornflower Lilac": "Cornflower Lilac",
  "Sundown": "Sundown",
  "My Sin": "My Sin",
  "Texas Rose": "Texas Rose",
  "Cotton Candy": "Algodão Doce",
  "Macaroni and Cheese": "Macarrão com Queijo",
  "Selective Yellow": "Amarelo Seletivo",
  "Koromiko": "Koromiko",
  "Amber": "Âmbar",
  "Wax Flower": "Flor de Cera",
  "Pink": "Rosa",
  "Your Pink": "Seu Rosa",
  "Supernova": "Supernova",
  "Flesh": "Flesh",
  "Sunglow": "Sunglow",
  "Golden Tainoi": "Golden Tainoi",
  "Peach Orange": "Peach Orange",
  "Chardonnay": "Chardonnay",
  "Pastel Pink": "Pastel Pink",
  "Romantic": "Romantic",
  "Grandis": "Grandis",
  "Gold": "Gold",
  "School bus Yellow": "School bus Yellow",
  "Cosmos": "Cosmos",
  "Mustard": " Mustard",
  "Peach Schnapps": "Peach Schnapps",
  "Caramel": "Caramel",
  "Tuft Bush": "Tuft Bush",
  "Watusi": "Watusi",
  "Pink Lace": "Pink Lace",
  "Navajo White": "Navajo White",
  "Frangipani": "Frangipani",
  "Pippin": "Pippin",
  "Pale Rose": "Pale Rose",
  "Negroni": "Negroni",
  "Cream Brulee": "Cream Brulee",
  "Peach": "Peach",
  "Tequila": "Tequila",
  "Kournikova": "Kournikova",
  "Sandy Beach": "Sandy Beach",
  "Karry": "Karry",
  "Broom": "Broom",
  "Colonial White": "Colonial White",
  "Derby": "Derby",
  "Vis Vis": "Vis Vis",
  "Egg White": "Egg White",
  "Papaya Whip": "Papaya Whip ",
  "Fair Pink": "Fair Pink",
  "Peach Cream": "Creme de Pêssego",
  "Lavender blush": "Bush de Lavanda",
  "Gorse": "Gorse",
  "Buttermilk": "Buttermilk",
  "Pink Lady": "Pink Lady",
  "Forget Me Not": "Forget Me Not",
  "Tutu": "Tutu",
  "Picasso": "Picasso",
  "Chardon": "Chardon",
  "Paris Daisy": "Paris Daisy",
  "Barley White": "Barley White",
  "Egg Sour": "Egg Sour",
  "Sazerac": "Sazerac",
  "Serenade": "Serenade",
  "Chablis": "Chablis",
  "Seashell Peach": "Seashell Peach",
  "Sauvignon": "Sauvignon",
  "Milk Punch": "Milk Punch",
  "Varden": "Varden",
  "Rose White": "Rose White",
  "Baja White": "Baja White",
  "Gin Fizz": "Gin Fizz",
  "Early Dawn": "Early Dawn",
  "Lemon Chiffon": "Lemon Chiffon",
  "Bridal Heath": "Bridal Heath",
  "Scotch Mist": "Scotch Mist",
  "Soapstone": "Soapstone",
  "Witch Haze": "Witch Haze",
  "Buttery White": "Buttery White",
  "Island Spice": "Island Spice",
  "Cream": "Cream",
  "Chilean Heath": "Chilean Heath",
  "Travertine": "Travertine",
  "Orchid White": "Orchid White",
  "Quarter Pearl Lusta": "Quarter Pearl Lusta",
  "Half and Half": "Half and Half",
  "Apricot White": "Damasco Branco",
  "Rice Cake": "Bolo de Arroz",
};

Future<void> saveUserToken(String token) async {
  const storage = FlutterSecureStorage();
  await storage.write(key: 'token', value: token);
}

Future getUserToken() async {
  const storage = FlutterSecureStorage();
  return await storage.read(key: 'token');
}

List<List<dynamic>> sliceArray(List<dynamic> data) {
  List<List<dynamic>> backup = [];
  int i = 0;
  int length = data.length;

  while (i < length) {
    if (backup.isEmpty || backup[backup.length - 1].length == 1) {
      if (data.elementAtOrNull(i + 1) == null) {
        backup.add([data[i]]);
      } else {
        backup.add([data[i], data[i + 1]]);
      }
      i += 2;
    } else if (backup[backup.length - 1].length == 2) {
      backup.add([data[i]]);
      i++;
    }
  }

  return backup;
}

int getPercentage(List data, String value) {
  return (((data.indexOf(value) + 1) / data.length) * 100).floor();
}

String slugify(String word) {
  final slug = word.toLowerCase().replaceAll(RegExp(r'[^a-z0-9]+'), '-');

  return slug.replaceAll(RegExp(r'^-|-$'), '');
}

List logoStatus = [
  "Aguardando Briefing",
  "Briefing Enviado",
  "Em Criação",
  "Provas enviadas",
  "Provas Recusadas",
  "Provas Aprovadas",
  "Aguardando Arquivos",
  "Arquivos Enviados",
];

List socialStatus = [
  "Aguardando Briefing",
  "Briefing Enviado",
  "Em Planejamento",
  "Enviado Amostra",
  "Amostra Reprovada",
  "Amostra Aprovada",
  "Em Criação",
  "Enviado Para Aprovação",
  "Reprovado",
  "Aprovado",
  "Publicando",
  "Publicado",
];
List siteStatus = [
  "Aguardando Briefing",
  "Briefing Enviado",
  "Em Planejamento",
  "Em Definição",
  "Proposta do Site",
  "Esperando Aprovação",
  "Reprovado",
  "Aprovado",
  "Em Publicação",
  "Publicado",
];

String getCardNumber(cardnumber) {
  Map cards = {
    "visa": r"^4[0-9]{12}(?:[0-9]{3})",
    "mastercard": r"^5[1-5][0-9]{14}",
    "amex": r"^3[47][0-9]{13}",
    "discover": r"^6(?:011|5[0-9]{2})[0-9]{12}",
    "hipercard": r"^(606282\d{10}(\d{3})?)|(3841\d{15})",
    "elo":
        r"^((((636368)|(438935)|(504175)|(451416)|(636297))\d{0,10})|((5067)|(4576)|(4011))\d{0,12})",
    "jcb": r"^(?:2131|1800|35\d{3})\d{11}",
    "aura": r"^(5078\d{2})(\d{2})(\d{11})$"
  };

  Map cardLogo = {
    "visa":
        "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Visa_Inc._logo.svg/1280px-Visa_Inc._logo.svg.png",
    "mastercard":
        "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/Mastercard-logo.svg/1280px-Mastercard-logo.svg.png",
    "diners": "https://cdn-icons-png.flaticon.com/512/196/196548.png",
    "amex":
        "https://www.pngmart.com/files/13/American-Express-Logo-PNG-File.png",
    "hipercard": "https://logospng.org/wp-content/uploads/hipercard.png",
    "elo":
        "https://logodownload.org/wp-content/uploads/2017/04/elo-logo-1-1.png",
  };

  for (var flag in cards.keys) {
    if (RegExp(cards[flag]).hasMatch(cardnumber)) {
      return cardLogo[flag];
    }
  }
  return "";
}
